# Generated by Django 2.2.4 on 2022-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
