# Generated by Django 2.2.4 on 2022-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20220209_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hoppes',
            field=models.CharField(default='swimm', max_length=200),
            preserve_default=False,
        ),
    ]
